Published:
  fr: 'Publié le'
  de: 'Veröffentlicht am'
  cz: Zveřejněno
  es: 'Fecha de publicación'
  fi: Julkaistu
  it: 'Pubblicato il'
  nl: 'Geplaatst op'
  pl: 'Opublikowano w dniu'
  pt: Publicado

Updated:
  fr: 'Modifié le'
  es: Modificado
  de: 'Aktualisiert am'
  cz: Aktualizováno
  fi: Muokattu
  it: 'Modificato il'
  nl: 'Laatste update op'
  pl: 'Zmodyfikowano w dniu'
  pt: Atualizado

By:
  fr: Par
  es: Por
  de: Von
  it: Da
  nl: Door
  pl: Autor

In:
  fr: Dans
  es: En
  de: In
  cz: V
  it: In
  nl: In
  pl: W

Misc:
  fr: Divers
  it: Varie
  de: Verschiedenes
  cz: Různé
  es: Miscelánea
  fi: Sekalaista
  nl: Diversen
  pl: Różne
  pt: Diversos

Telecom:
  fr: Télécom
  it: Telecom
  de: Telekom
  cz: Telecom
  es: Telecom
  fi: Telekom
  nl: Telecom
  pl: Telekomunikacja
  pt: Telecom

Translations:
  fr: Traductions
  es: Traducción
  it: Traduzioni
  de: Übersetzungen
  cz: Překlady
  fi: Käännökset
  nl: Vertalingen
  pl: Tłumaczenia
  pt: Traduções

'OVH Guides':
  fr: 'Documentation OVH'
  es: 'OVH Guías'
  cz: 'Příručky OVH'
  it: 'Documentazione OVH'
  de: 'OVH Dokumentation'
  fi: 'OVH:n Ohjeet'
  nl: 'OVH-handleidingen'
  pl: 'Dokumentacja techniczna OVH'
  pt: 'Manuais OVH'

'Search OVH guides':
  fr: 'Rechercher dans la documentation OVH'
  cz: 'Prohledat příručky OVH'
  it: 'Cerca nella documentazione OVH'
  de: 'OVH Dokumentation durchsuchen'
  es: 'Buscar en la documentación de OVH'
  fi: 'Etsi OVH:n ohjeista'
  nl: 'Zoek OVH-handleidingen'
  pl: 'Szukaj w dokumentacji technicznej OVH'
  pt: 'Procurar Manuais'

'These guides might also interest you':
  fr: 'Ces guides pourraient également vous intéresser'
  es: 'Otras guías que podrían interesarle'
  cz: 'Mohlo by Vás zaujmout'
  de: 'Diese Anleitungen könnten Sie auch interessieren'
  it: 'Potrebbero interessarti anche'
  fi: 'Myös nämä ohjeet saattavat kiinnostaa sinua'
  nl: 'Deze handleidingen kunnen ook interessant zijn voor u'
  pl: 'Inne przewodniki, które mogą Cię zainteresować'
  pt: 'Estes manuais também podem ser úteis'

Share:
  fr: Partager
  cz: Sdílet
  it: Condividi
  de: Teilen
  es: Compartir
  fi: Jaa
  nl: Delen
  pl: Udostępnij
  pt: Partilha

Contribute:
  fr: Contribuer
  cz: Přispět
  de: Mitmachen
  it: Modifica
  fi: Muokkaa
  es: Contribuir
  nl: Bijdragen
  pl: Współtwórz
  pt: Contribuir

'Did you find this guide useful?':
  fr: 'Cette documentation vous a-t-elle été utile ?'
  es: '¿Le ha resultado útil esta guía?'
  it: 'Questa documentazione ti è stata utile?'
  nl: 'Vond u deze handleiding nuttig?'
  pt: 'Esta documentação foi-lhe útil?'
  de: 'Haben Ihnen die Anleitungen geholfen?'
  pl: 'Czy ten przewodnik był pomocny?'

'Yes':
  fr: 'Oui'
  es: 'Sí'
  it: 'Sì'
  nl: 'Ja'
  pt: 'Sim'
  de: 'Ja'
  pl: 'Tak'

"Great! We're glad we were able to help":
  fr: "Génial ! Ravi d'avoir pu vous aider"
  es: "¡Perfecto! Estamos encantados de poder ayudarle"
  it: "Benissimo! Siamo felici di averti aiutato"
  nl: "Geweldig! We zijn blij dat we konden helpen"
  pt: "Ótimo! Ficamos contentes por poder ajudar"
  de: "Schön, dass wir Ihnen helfen konnten"
  pl: "Cieszymy się, że mogliśmy pomóc"

'No':
  fr: 'Non'
  es: 'No'
  it: 'No'
  nl: 'Nee'
  pt: 'Não'
  de: 'Nein'
  pl: 'Nie'

'Whether your feedback is about images, content, or structure, please share it, so that we can improve it together.':
  fr: "Images, contenu, structure… N’hésitez pas à nous dire pourquoi afin de la faire évoluer ensemble !"
  es: "Imágenes, contenido, estructura...: ayúdenos a mejorar nuestra documentación con sus sugerencias."
  it: "Immagini, contenuti, struttura... Spiegaci perché, così possiamo migliorarla insieme!"
  nl: "Waarom was het niet nuttig?"
  pt: "Imagens, conteúdo, estrutura... Não hesite em dizer-nos porquê para evoluirmos em conjunto!"
  de: "Woran liegt es? An den Bildern, dem Inhalt oder Aufbau der Anleitungen? Schreiben Sie es uns gerne, dann machen wir es zusammen besser."
  pl: "Obrazy, zawartość, struktura - podziel się swoim pomysłem, my dołożymy wszelkich starań, aby wprowadzić ulepszenia."

Send:
  fr: 'Envoyer'
  es: 'Enviar'
  it: 'Invia'
  nl: 'Verzenden'
  pt: 'Enviar'
  de: 'Absenden'
  pl: 'Wyślij'

'Thank you. Your feedback has been received':
  fr: 'Merci beaucoup pour votre aide ! Vos retours seront étudiés au plus vite par nos équipes.'
  es: '¡Gracias! Tendremos en cuenta su opinión'
  it: 'Grazie per averci inviato il tuo feedback'
  nl: 'Hartelijk bedankt, uw feedback is ontvangen'
  pt: 'Obrigado. A sua mensagem foi recebida com sucesso'
  de: 'Vielen Dank. Ihr Feedback wurde gesendet'
  pl: 'Dziękujemy. Twoja opinia jest dla nas bardzo cenna'

'Please feel free to give any suggestions in order to improve this documentation.':
  fr: "N’hésitez pas à nous proposer des suggestions d’amélioration afin de faire évoluer cette documentation."
  de: "Bevor Sie Ihre Meinung abgeben, nehmen wir gerne Ihre Vorschläge auf, wie wir diese Dokumente verbessern können."
  es: "Si lo desea, también puede enviarnos sus sugerencias para ayudarnos a mejorar nuestra documentación."
  it: "Prima di inviare la valutazione, proponici dei suggerimenti per migliorare la documentazione."
  pl: "Zachęcamy do przesyłania sugestii, które pomogą nam ulepszyć naszą dokumentację."
  pt: "Não hesite em propor-nos sugestões de melhoria para fazer evoluir este manual."

'Your support requests will not be processed via this form. To do this, please use the':
  fr: "Vos demandes d’assistance ne seront pas traitées par ce formulaire. Pour cela, utilisez le formulaire"
  de: "Ihre Support-Anfragen werden in diesem Formular nicht entgegengenommen. Verwenden Sie hierfür bitte das Formular"
  es: "No podemos tratar sus solicitudes de asistencia a través de este formulario. Para ello, haga clic en"
  it: "Le richieste di assistenza non sono gestite con questo form. Se ti serve supporto, utilizza il form"
  pl: "Zgłoszenie przesłane za pomocą tego formularza nie zostanie obsłużone. Skorzystaj z formularza"
  pt: "Os seus pedidos de assistência não serão tratados através deste formulário. Para isso, utilize o formulário"

'Create a ticket':
  fr: "Créer un ticket"
  de: "Ein Ticket erstellen"
  es: "Crear un tíquet"
  it: "Crea un ticket"
  pl: "Utwórz zgłoszenie"
  pt: "Criar um ticket"

Print:
  fr: Imprimer
  de: Drucken
  es: Imprimir
  it: Stampare
  pl: Drukuj
  pt: Imprimir

'OVHcloud Community':
  fr: 'OVHcloud Community'

"Access your community space. Ask questions, search for information, post content, and interact with other OVHcloud Community members.":
  fr: "Accédez à votre espace communautaire. Posez vos questions, recherchez des informations, publiez du contenu et interagissez avec d'autres membres d'OVHcloud Community."

'Visit OVHcloud Community':
  fr: 'Visitez OVHcloud Community'

'IP management':
  fr: 'Gestion des IP'
  es: 'Gestión de direcciones IP'
  it: 'Gestione degli IP'

'Customer data protection':
  fr: 'Protection de données client'
  es: 'Protección de datos del cliente'
  it: 'Protezione dei dati dei clienti'

'Instance management':
  fr: 'Gestion des instances'
  es: 'Gestión de instancias'
  it: 'Gestione delle istanze'

'Managing dedicated servers':
  fr: 'Gestion des serveurs dédiés'
  es: 'Gestión de servidores dedicados'
  it: 'Gestione dei server dedicati'

'VPS management':
  fr: 'Gestion des VPS'
  es: 'Gestión de VPS'
  it: 'Gestione dei VPS'

'https://docs.ovh.com/gb/en/dedicated/ip-fo-move/':
  fr: 'https://docs.ovh.com/fr/dedicated/ip-fo-move/'

'https://docs.ovh.com/gb/en/public-cloud/make-failover-ip-configuration-persistent/':
  fr: 'https://docs.ovh.com/fr/public-cloud/rendre-la-configuration-ip-fail-over-persistante/#configuration-de-lip-fail-over_1'

'https://docs.ovh.com/gb/en/public-cloud/configure_a_failover_ip/':
  fr: 'https://docs.ovh.com/fr/public-cloud/configurer_une_ip_failover/'

'https://docs.ovh.com/gb/en/customer/scams-fraud-phishing/':
  fr: 'https://docs.ovh.com/fr/customer/arnaques-fraude-phishing/'

'https://docs.ovh.com/gb/en/customer/secure-account-with-2FA/':
  fr: 'https://docs.ovh.com/fr/customer/securiser-son-compte-avec-une-2FA/'

'https://docs.ovh.com/gb/en/public-cloud/increase-public-cloud-quota/':
  fr: 'https://docs.ovh.com/fr/public-cloud/augmenter-le-quota-public-cloud/'

'https://docs.ovh.com/gb/en/public-cloud/get-started-with-a-public-cloud-instance/#reboot-an-instance':
  fr: 'https://docs.ovh.com/fr/public-cloud/debuter-avec-une-instance-public-cloud/#redemarrer-une-instance'

'https://docs.ovh.com/gb/en/dedicated/ovh-rescue/#instructions':
  fr: 'Https://docs.ovh.com/fr/dedicated/ovh-rescue/#en-pratique'

'https://docs.ovh.com/gb/en/dedicated/use-ipmi-dedicated-servers/':
  fr: 'https://docs.ovh.com/fr/dedicated/utilisation-ipmi-serveurs-dedies/'

'https://docs.ovh.com/gb/en/dedicated/services-backup-storage/#accessbackup':
  fr: 'https://docs.ovh.com/fr/dedicated/services-backup-storage/#accessbackup'

'https://docs.ovh.com/gb/en//vps/vps-faq/#backupstorage':
  fr: 'https://docs.ovh.com/fr/vps/vps-faq/#backupstorage'

'https://docs.ovh.com/gb/en/vps/getting-started-vps/#reboot-current-range':
  fr: 'https://docs.ovh.com/fr/vps/debuter-avec-vps/#reboot-current-range'

'Move a failover IP':
  fr: 'Déplacer une IP Failover'
  es: 'Mover una IP Failover'
  it: 'Trasferisci un IP failover'

'Make a failover IP configuration persistent':
  fr: 'Rendre la configuration IP Failover persistante'
  es: 'Hacer persistente la configuración de IP Failover'
  it: 'Configura un IP Failover permanente'

'Import a failover IP':
  fr: 'Configurer une IP Failover'
  es: 'Configurar una IP Failover'
  it: 'Importa un IP Failover'

'Recognising fraud and phishing emails/SMS messages':
  fr: 'Reconnaître des e-mails ou SMS de fraude et de phishing'
  es: 'Detectar los mensajes de correo o SMS fraudulentos y el phishing'
  it: 'Come riconoscere email fraudolente e di phishing'

'Securing OVHcloud accounts with two-factor authentication':
  fr: 'Sécuriser son compte OVHcloud avec la double authentification'
  es: 'Proteger su cuenta de OVHcloud con la doble autenticación'
  it: 'Rendere sicuro il tuo account OVHcloud con la doppia autenticazione'

'Increasing the quota of Public Cloud instances':
  fr: 'Augmenter le quota des instances Public Cloud'
  es: 'Aumentar el límite de las instancias Public Cloud'
  it: 'Aumentare la quota delle istanze Public Cloud'

'Rebooting a Public Cloud instance':
  fr: 'Redémarrer une instance Public Cloud'
  es: 'Reiniciar una instancia Public Cloud'
  it: "Riavviare un'istanza Public Cloud"

'Activating and using rescue mode':
  fr: 'Activer et utiliser le mode rescue'
  es: 'Activar y utilizar el modo de rescate'
  it: 'Attivare e utilizzare la modalità Rescue'

'Using the IPMI with dedicated servers':
  fr: 'Utiliser l’IPMI pour les serveurs dédiés'
  es: 'Utilizar IPMI en un servidor dedicado'
  it: "Utilizzare l'IPMI sui server dedicati"

'Enabling backup storage on a dedicated server':
  fr: 'Activer Backup Storage sur un serveur dédié'
  es: 'Utilizar Backup Storage en un servidor dedicado'
  it: "Attivare il Backup Storage su un server dedicato"

'Access your backup':
  fr: 'Accéder à votre backup'
  es: 'Acceder a su backup'
  it: 'Accedi al backup'

'Reboot a VPS':
  fr: 'Redemarrer un VPS'
  es: 'Reiniciar un VPS'
  it: 'Riavvia un VPS'

'Most consulted guides':
  fr: 'Les tutoriels les plus consultés'
